name: Test and lint

on: push

jobs:
  test-n-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
      - name: Flake8 linting
        run: |
          poetry run flake8 . --select=E9,F63,F7,F82
          poetry run flake8 . --exit-zero
      - name: Test with pytest
        run: |
          poetry run pytest

  trigger_publish:
    runs-on: ubuntu-latest
    needs: [test-n-lint]
    steps:
      - name: Trigger publish
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
